<?php include_once("header.php");
print "<h2 class='text-center'>Sobre AFAJE</h2>";
print "<div class='alert mt-3'>";
print "<img src='img/vivero.jpg' class='rounded float-end img-fluid mx-auto'/>";
print "<p>
Bienvenido a AFAJE. Somos un grupo de jóvenes que tenemos unas ganas enormes de trabajar. Somos 11 chicos y 4 chicas de Ayamonte, en la provincia de Huelva. Nuestro pueblo es muy bonito, tiene playa y río y precisamente el río es lo que nos separa de otro país, Portugal. Siempre se ha pensado que la vida laboral es necesaria para sentirnos ciudadanos completos. AFAJE, es un colectivo de personas con discapacidad intelectual que esta convencido de esa afirmacion y lucha para conseguir la inclusión laboral. No es facil pero estamos sabemos  que con la formación adecuada podemos triunfar en ese objetivo. Por eso la mayoría de nuestros proyectos se basan en la formacion y preparación profesional. ¿Cuáles son esos proyectos? Actualmente, tenemos un vivero de plantas en el parque de nuestra ciudad, Ayamonte, en él trabajamos duro para producir plantas que luego colocamos en los jardines de plazas y calles, aprendiendo los rudimentos de la jardinería. Nuestro vivero tiene un magnífico entorno rodeado de naturaleza por eso hemos empezado un nuevo proyecto que consiste en recibir a los escolares de los centros educativos de los alrededores para realizar talleres en los que puedan apreciar el valor de las plantas en la vida cotidiana y las respeten por su importancia. También tenemos una tienda física, solidaria, en la que vendemos ropa y accesorios que nos donan otras tiendas. Estamos muy ilusionados con esta tienda online que nos permite conocer a mucha mas gente y ademas nos proporciona ingresos para poner en marcha los nuevos proyectos. También queremos hablar de una actividad que no es formativa pero que nos gusta a todos y en la que participamos con gran ilusión, se trata de un equipo de futbol inclusivo que nos permite relacionarnos con chicos y chicas de otros lugares y cubre una parte muy importante de nuestra formación como personas, como es el ocio y la ocupación del tiempo libre. 
bueno tenemos muchas cosas que contar y nos gustaría que de vez en cuando te asomes a esta ventana y podamos mantener un contacto, te contaremos nuestras novedades y tu podras contarnos cosas, además prometemos actualizar nuestra tienda de vez en cuando para que puedas disfrutar de sus novedades. Si quieres contactar con nocostros, puedes hacerlo por correo electronico afajeayamonte@gmail.com
Si vienes a Ayamonte estamos en el parque Prudencio Navarro o en nuestra sede en la calle LUis Braille s/n, junto al mercado de abastos. 
</p>";
print "</div>";
print "<a href='".RUTAAPP."tienda' class='btn btn-success'/>Volver</a>";
include_once("footer.php"); ?>
